### ISSUE TITLE
I can't run this code

### ISSUE THREAD

**Issue by rgd66** [krishnabits001/task_driven_data_augmentation#2]
When I run this code, I missed this problem:FileNotFoundError: [Errno 2] No such file or directory: '/usr/bmicnas01/data-biwi-01/krishnch/datasets/heart_acdc/acdc_bias_corr_cropped/patient002/img_cropped.npy'

I don't know how create this file and can you tell me more details?

**Comment by krishnabits001** [comment]
Hi,
Can you please kindly check the instructions provided in ReadME in section III) Dataset download.
As stated there if you want to use numpy (.npy) files to load the pre-processed data, you need to create them first using the provided file "create_cropped_imgs_acdc.py". 
Please kindly set the path of the variables like base_dir, data_path_tr,data_path_tr_cropped appropriately in the "init_acdc.py" file under the "experiment_init" folder before running the above file.

If you do not want to create numpy files, please modify the data loading function in *.py in train_model accordingly to read the nifti files directly and pre-process them into the stated dimensions and resolution using "preprocess_data" function in dataloaders.py file.
